# Inclusion and Exclusion Criteria

> Create a numbered list below in sections 3.1 and 3.2 of criteria
> subjects must meet to be eligible for study enrollment (e.g., age,
> gender, diagnosis, etc.).
> 
> **Vulnerable Populations:**
> 
> You MAY NOT include members of these populations as subjects in your
> research unless you indicate this in your inclusion criteria because
> specific regulations apply to studies that involve vulnerable
> populations.
> 
> The checklists referenced below outline the determinations to be made
> by the IRB when reviewing research involving these populations. Review
> the checklists as these will help to inform your responses throughout
> the remainder of the protocol.
> 
> -   **Children --**Review "HRP-416- Checklist - Children"
> 
> -   **Pregnant Women** -- Review "HRP-412- Checklist - Pregnant Women"
> 
> -   **Cognitively Impaired Adults-** Review "HRP-417- Checklist - Cognitively Impaired Adults"
> 
> -   **Prisoners-** Review "HRP-415- Checklist - Prisoners"
> 
> -   **Neonates of uncertain viability or non-viable neonates-** Review "HRP-413- Checklist - Non-Viable Neonates" or "HRP-414- Checklist - Neonates of Uncertain Viability"

## Inclusion Criteria

> Create a numbered list of the inclusion criteria that define who will be included in your final study sample (e.g., age, gender, condition, etc.)

1. Graduate students, postdocs, teaching faculty, research staff, research faculty, and administrators at Penn State, all 18+ years of age or older and of any gender.

### Does this research involve collecting data from individuals residing outside of the US?

[X] No</br>
[ ] Yes -- identify the countries where data collection will take place

## Exclusion Criteria

> Create a numbered list of the exclusion criteria that define who will be excluded in your study.

1. Participants younger than 18 years of age.
2. Participants not associated with Penn State in one of the included roles.

## Early Withdrawal of Subjects

### Criteria for removal from study

> Insert subject withdrawal criteria (e.g., safety reasons, failure of subject to adhere to protocol requirements, subject consent withdrawal, disease progression, etc.).

Subjects can withdraw from the survey at any time and for any reason. 

### Follow-up for withdrawn subjects

> Describe when and how to withdraw subjects from the study; the type and timing of the data to be collected for withdrawal of subjects; whether and how subjects are to be replaced; the follow-up for subjects withdrawn from investigational treatment.

Because this is an online survey, subjects can withdraw by closing the web browser that they are using to take the survey.
No follow-up or subject replacement will occur for subjects who withdraw.  
