# Consent Process and Documentation

## Consent Process

## Obtaining Informed Consent

### Consent Process

### Coercion or Undue Influence during Consent

## Waiver of Written Documentation of Consent

### Indicate which of the following conditions applies to this research:

### Indicate what materials, if any, will be used to inform potential subjects about the research (e.g., a letter accompanying a questionnaire, verbal script, or implied consent form).


## Informed consent will be sought but some of the elements of informed consent will be omitted or altered (e.g., deception).

### Indicate the elements of informed consent to be omitted or altered.

### Indicate why the research could not practicably be carried out without the omission or alteration of consent elements

### Describe why the research involves no more than minimal risk to subjects.

### Describe why the alteration/omission will not adversely affect the rights and welfare of subjects.

### If the research involves using identifiable private information or identifiable biospecimens, describe why the research could not practicably be carried out without using such information or biospecimens in an identifiable format.

### Debriefing

## Informed consent will not be obtained – request to completely waive the informed consent requirement

### Indicate why the research could not practicably be carried out without the waiver of consent.

### Describe why the research involves no more than minimal risk to subjects.

### Describe why the alteration/omission will not adversely affect the rights and welfare of subjects.

### If the research involves using identifiable private information or identifiable biospecimens, describe why the research could not practicably be carried out without using such information or biospecimens in an identifiable format.

### Additional pertinent information after participation.

## Consent – Other Considerations

### Non-English-Speaking Subjects

### Cognitively Impaired Adults

#### Capability of Providing Consent

#### Adults Unable to Consent

#### Assent of Adults Unable to Consent

### Subjects who are not yet adults (infants, children, teenagers)

#### Parental Permission

#### Assent of subjects who are not yet adults


