# Resources Available

## Facilities and locations

::: {.instr_box}

Identify and describe the facilities, sites, and locations where
recruitment and study procedures will be performed.

If research will be conducted outside the United States, describe
site-specific regulations or customs affecting the research, and
describe the process for obtaining local ethical review. Also,
describe the principal investigator's experience conducting research
at these locations and familiarity with local culture.

[Type protocol text here]

:::

The survey will be conducted online using Penn State's email servers, a Google Form, and Google Sheets.

## Feasibility of recruiting the required number of subjects

::: {.instr_box}

Indicate the number of potential subjects to which the study team has
access. Indicate the percentage of those potential subjects needed for
recruitment.

[Type protocol text here]

:::

According to <https://datadigest.psu.edu/faculty-and-staff/>, there are more than 6,400 full-time and 4,980 part-time faculty; 400+ administrators; 6,000+ graduate students and postdocs; and more than 10,000 staff.
So, the potential number of respondents exceeds 20,000.

We hope to achieve a 5-10% response rate among faculty, postdocs, and graduate students.
That would result in 850-1,700 responses.

## PI Time devoted to conducting the research

::: {.instr_box}

Describe how the PI will ensure that a sufficient amount of time will
be devoted to conducting and completing the research. Consider outside
responsibilities as well as other on-going research for which the PI
is responsible. Please only provide a response for the principal
investigator -- do **not** include information about any other study
team members.

[Type protocol text here]

:::

The investigator will allocate time during the week to collect and analyze data, and to writing any relevant manuscripts. 

## Availability of medical or psychological resources

::: {.instr_box}
Describe the availability of medical or psychological resources that
subjects might need as a result of their participation in the study.

[Type protocol text here or indicate as not applicable]

:::

Not applicable.

## Process for informing Study Team

::: {.instr_box}

Describe the training plans to ensure members of the research team are informed about the protocol and their duties.

[Type protocol text here or indicate as not applicable if the principal investigator is the only study team member listed on the CATS IRB submission]

:::

Our entire protocol for this study is open and available to anyone, including the research team.
The research team meets every other week to discuss the project.

