# (PART) IRB Supplemental {-}

# Survey language and questions {-}

## Email to prospective participants {- #email-to-participants}

> Dear Penn Stater:
> 
> We are a group of faculty who are interested in knowing more about what students, postdocs, staff, faculty, and adminstrators know about open science practices and whether they incorporate open science practices into their research.</br>
> Our goal is to determine whether there is a need for a center that provides training and support for open science practices.</br>
> To that end, we have devised a short survey that should take you no more than 10 min to complete.
> The survey is created using a Google Form, and unless you decide to provide us with your name and email, no identifiable information will be collected.
>
> Survey link: <https://forms.gle/BpK1Zsyw1k3tVnSE7>
>
> Once we have analyzed the results, we plan to share them with the Penn State community
>
> Thank you for your consideration.
>
> Yours truly,
>
> Rick Gilmore, Department of Psychology</br>
> Frank Hillary, Department of Psychology</br>
> Nicole Lazar, Department of Statistics</br>
> Briana Wham, University Libraries

## Survey introduction {-}

> We are asking you to be in a research study. Whether or not you take part is up to you. You can choose not to take part. You can agree to take part and later change your mind. Your decision will not be held against you, and there will be no penalty.</br>
> The study involves a taking a brief survey. The survey focuses on data management and sharing practices and principles of open science. Unless you provide us your name and/or contact information, your responses are anonymous. If you provide us your name or contact information we may contact you at a later time.</br>
> The target audience for the survey is Penn State students, faculty, and staff who are over the age of 18. If you are not 18 and not a Penn State student, faculty member, or staff member, please do not take this survey.

## Survey questions {- #survey-questions}

**Note**: Here is a useful reference for what language to use for Likert scale questions <https://www.extension.iastate.edu/documents/anr/likertscaleexamplesforsurveys.pdf>

```{r}
suppressPackageStartupMessages(library("tidyverse")) # for pipe %>% operator

# Read local copy of survey
survey <- readr::read_csv("csv/open-science-survey-2022-fall.csv")

# Drop the Timestamp since it is provided by Google Forms automatically
survey_questions <- names(survey)[2:dim(survey)[2]]

survey_questions %>%
  kableExtra::kbl(.) %>%
  kableExtra::kable_classic(.)
```
