# Background

## Scientific Background and Gaps

::: {.instr_box}
Describe the scientific background and gaps in current knowledge.
For clinical research studies being conducted at Penn State
Health/Penn State College of Medicine, and for other non-PSH locations
as applicable, describe the treatment/procedure that is considered
standard of care (i.e., indicate how patients would be treated in
non-investigational setting); and if applicable, indicate if the study
procedure is available to patient without taking part in the study.
:::

There is a growing movement in the scientific community towards more openness and transparency: data and code sharing; open access publishing; pre-registration, etc.
In part this is in reaction to a perceived crisis of reproducibility and replicability; in part it is due to many high-profile examples of “questionable research practices.”
 
## Previous Data

::: {.instr_box}
Describe any relevant preliminary data.
:::

The Penn State Libraries conducted a survey of researchers in the physical sciences on somewhat related topics in the last year. That survey was determined to be exempt. Outside of that survey, little is currently known about researchers' knowledge about common Open Science practices and principles.  

One of the investigators (Lazar) is part of a team that conducted a similar survey at the University of Georgia focused on graduate students. They found that knowledge about Open Science varies by student field of study. They also found clusters of practices that had similar levels of familiarity among the students. Lazar has recently collected data from but not analyzed some similar survey questions from graduate students in the Huck Institute of the Life Sciences graduate program. This survey (STUDY00021123) was also determined by the PSU IRB to be exempt.

## Study Rationale

::: {.instr_box}
Provide the scientific rationale for the research.
:::

The investigators believe that there is significant need for more organized and focal educational activities and project-specific support related to Open Science.
This survey will characterize the current state of knowledge and need for these sorts of activities at Penn State.
