# Risks

::: {.instr_box .rmdnote}

List the reasonably foreseeable risks, discomforts, hazards, or inconveniences to the subjects related the subjects' participation in the research. Include as may be useful for the IRB's consideration, a description of the probability, magnitude, duration, and reversibility of the risks.
Consider all types of risk including physical, psychological, social, legal, and economic risks.
**Note: Loss of confidentiality is a potential risk when conducting human subject research and must be listed here.**
-   If applicable, indicate which procedures may have risks to the
subjects that are currently unforeseeable.
-   If applicable, indicate which procedures may have risks to an embryo
or fetus should the subject be or become pregnant.
-   If applicable, describe risks to others who are not subjects.

:::

The study poses minimal risk beyond the potential for loss of confidentiality. 
The items are non-sensitive and hold little potential to cause psychological distress.
General steps to ensure confidentiality are as follows: (1) all data files and responses will be stored on password protected servers and personal computers; (2) only investigators listed on this application will have access to the raw data; (3) data will be presented in aggregated form. 
